function autoPopulateSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName("Products");
  
  if (!sheet) {
    sheet = ss.insertSheet("Products");
  }

  const data = [
    ["id","category_en","category_ar","name_en","name_ar","price","availability","order","image_key"],
    [1,"Duck Espresso Corner","ركن الإسبريسو","Spanish Latte","سبانش لاتيه","105",true,1,"espresso.jpeg"],
    [2,"Duck Espresso Corner","ركن الإسبريسو","Latte","لاتيه","80",true,2,"espresso.jpeg"],
    [3,"Duck Espresso Corner","ركن الإسبريسو","Cappuccino","كابتشينو","90",true,3,"espresso.jpeg"],
    [4,"Duck Espresso Corner","ركن الإسبريسو","Flat White","فلات وايت","70",true,4,"espresso.jpeg"],
    [5,"Duck Espresso Corner","ركن الإسبريسو","Mocha","موكا","85",true,5,"espresso.jpeg"],
    [6,"Duck Espresso Corner","ركن الإسبريسو","Caramel Mocha","كراميل موكا","95",true,6,"espresso.jpeg"],
    [7,"Duck Espresso Corner","ركن الإسبريسو","Caramel Macchiato","كراميل ماكياتو","95",true,7,"espresso.jpeg"],
    [8,"Duck Espresso Corner","ركن الإسبريسو","Hot Chocolate","هوت شوكليت","90",true,8,"espresso.jpeg"],
    [9,"Duck Espresso Corner","ركن الإسبريسو","Dulce De Leche Latte","دولسي دي ليتشي لاتيه","95",true,9,"espresso.jpeg"],
    [10,"Duck Espresso Corner","ركن الإسبريسو","Espresso (S/D)","إسبريسو (سنجل/دبل)","45 / 55",true,10,"espresso.jpeg"],
    [11,"Duck Espresso Corner","ركن الإسبريسو","Espresso Macchiato (S/D)","إسبريسو ماكياتو (سنجل/دبل)","50 / 60",true,11,"espresso.jpeg"],
    [12,"Duck Espresso Corner","ركن الإسبريسو","Cortado","كورتادو","65",true,12,"espresso.jpeg"],
    [13,"Duck Espresso Corner","ركن الإسبريسو","Americano (M/L)","أمريكانو (وسط/كبير)","60 / 70",true,13,"espresso.jpeg"],
    [14,"Duck Espresso Corner","ركن الإسبريسو","Hot Chocolate Marshmallow","هوت شوكليت مارشميلو","120",true,14,"espresso.jpeg"],
    [15,"Duck Hot Corner","مشروبات ساخنة","English Tea (M/L)","شاي إنجليزي (وسط/كبير)","40 / 50",true,1,"hot1.jpeg"],
    [16,"Duck Hot Corner","مشروبات ساخنة","Green Tea (M/L)","شاي أخضر (وسط/كبير)","40 / 50",true,2,"hot1.jpeg"],
    [17,"Duck Hot Corner","مشروبات ساخنة","Earl Grey Tea (M/L)","شاي إيرل جراي (وسط/كبير)","40 / 50",true,3,"hot1.jpeg"],
    [18,"Duck Hot Corner","مشروبات ساخنة","Anise (M/L)","يانسون (وسط/كبير)","35 / 45",true,4,"hot1.jpeg"],
    [19,"Duck Hot Corner","مشروبات ساخنة","Roselle (M/L)","كركديه (وسط/كبير)","35 / 45",true,5,"hot1.jpeg"],
    [20,"Duck Hot Corner","مشروبات ساخنة","Mint (M/L)","نعناع (وسط/كبير)","35 / 45",true,6,"hot1.jpeg"],
    [21,"Duck Hot Corner","مشروبات ساخنة","Lemon Ginger (M/L)","ليمون بالزنجبيل (وسط/كبير)","35 / 45",true,7,"hot1.jpeg"],
    [22,"Duck Hot Corner","مشروبات ساخنة","Herbs (M/L)","أعشاب (وسط/كبير)","50 / 60",true,8,"hot1.jpeg"],
    [23,"Duck Hot Corner","مشروبات ساخنة","Flavored Tea (M/L)","شاي بنكهات (وسط/كبير)","50 / 60",true,9,"hot1.jpeg"],
    [24,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Tea With Milk (M/L)","شاي بحليب (وسط/كبير)","50 / 60",true,1,"hot.jpeg"],
    [25,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Nescafe With Milk (M/L)","نسكافيه بالحليب (وسط/كبير)","50 / 65",true,2,"hot.jpeg"],
    [26,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Nescafe Black","نسكافيه بلاك","35 / 50",true,3,"hot.jpeg"],
    [27,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Hot Cider","هوت سيدر","80",true,4,"hot.jpeg"],
    [28,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Cinnamon With Milk","قرفة بالحليب","50 / 60",true,5,"hot.jpeg"],
    [29,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Sahlab Nuts","سحلب بالمكسرات","75",true,6,"hot.jpeg"],
    [30,"Duck Hot Corner (2)","مشروبات ساخنة (2)","Karak Tea","شاي كرك","70",true,7,"hot.jpeg"],
    [31,"Duck Coffee Corner","ركن القهوة","Turkish Coffee (S/D)","قهوة تركي (سنجل/دبل)","40 / 60",true,1,"coffee.jpeg"],
    [32,"Duck Coffee Corner","ركن القهوة","French Coffee (S/D)","قهوة فرنساوي (سنجل/دبل)","45 / 65",true,2,"coffee.jpeg"],
    [33,"Duck Coffee Corner","ركن القهوة","Hazelnut Coffee (S/D)","قهوة بالبندق (سنجل/دبل)","50 / 70",true,3,"coffee.jpeg"],
    [34,"Duck Coffee Corner","ركن القهوة","Nutella Coffee (S/D)","قهوة نوتيلا (سنجل/دبل)","55 / 75",true,4,"coffee.jpeg"],
    [35,"Duck Iced Corner","ركن المثلجات","Ice Latte","أيس لاتيه","90",true,1,"iced.jpeg"],
    [36,"Duck Iced Corner","ركن المثلجات","Ice Chocolate","أيس شوكليت","90",true,2,"iced.jpeg"],
    [37,"Duck Iced Corner","ركن المثلجات","Ice Mocha","أيس موكا","95",true,3,"iced.jpeg"],
    [38,"Duck Iced Corner","ركن المثلجات","Ice Dulce De Leche","أيس دولسي دي ليتشي","95",true,4,"iced.jpeg"],
    [39,"Duck Iced Corner","ركن المثلجات","Ice Spanish Latte","أيس سبانش لاتيه","105",true,5,"iced.jpeg"],
    [40,"Duck Iced Corner","ركن المثلجات","Ice Caramel Macchiato","أيس كراميل ماكياتو","95",true,6,"iced.jpeg"],
    [41,"Duck Iced Corner","ركن المثلجات","Ice Americano","أيس أمريكانو","70",true,7,"iced.jpeg"],
    [42,"Duck Frappe Corner","ركن الفرابيه","Caramel Frappe","فرابيه كراميل","95",true,1,"frappe.jpeg"],
    [43,"Duck Frappe Corner","ركن الفرابيه","Vanilla Frappe","فرابيه فانيليا","95",true,2,"frappe.jpeg"],
    [44,"Duck Frappe Corner","ركن الفرابيه","Hazelnut Frappe","فرابيه بندق","95",true,3,"frappe.jpeg"],
    [45,"Duck Frappe Corner","ركن الفرابيه","Mocha Frappe","فرابيه موكا","95",true,4,"frappe.jpeg"],
    [46,"Duck Frappe Corner","ركن الفرابيه","Dulce De Leche Frappe","فرابيه دولسي دي ليتشي","95",true,5,"frappe.jpeg"],
    [47,"Duck Frappe Corner","ركن الفرابيه","Strawberry Frappe","فرابيه فراولة","95",true,6,"frappe.jpeg"],
    [48,"Duck Frappe Corner","ركن الفرابيه","Peach Frappe","فرابيه خوخ","95",true,7,"frappe.jpeg"],
    [49,"Duck Frappe Corner","ركن الفرابيه","Oreo Frappe","فرابيه أوريو","95",true,8,"frappe.jpeg"],
    [50,"Duck Frappe Corner","ركن الفرابيه","Spanish Frappe","فرابيه سبانش","105",true,9,"frappe.jpeg"],
    [51,"Duck Frappe Corner","ركن الفرابيه","Peanut Butter Frappe","فرابيه زبدة الفول السوداني","105",true,10,"frappe.jpeg"],
    [52,"Duck Yogurt Corner","ركن الزبادي","Strawberry Yogurt","زبادي فراولة","90",true,1,"yogurt.jpeg"],
    [53,"Duck Yogurt Corner","ركن الزبادي","Peach Yogurt","زبادي خوخ","90",true,2,"yogurt.jpeg"],
    [54,"Duck Yogurt Corner","ركن الزبادي","Kiwi Yogurt","زبادي كيوي","90",true,3,"yogurt.jpeg"],
    [55,"Duck Yogurt Corner","ركن الزبادي","Mango Yogurt","زبادي مانجو","90",true,4,"yogurt.jpeg"],
    [56,"Duck Yogurt Corner","ركن الزبادي","Blueberry Yogurt","زبادي توت أزرق","90",true,5,"yogurt.jpeg"],
    [57,"Duck Yogurt Corner","ركن الزبادي","Honey Yogurt","زبادي عسل","90",true,6,"yogurt.jpeg"],
    [58,"Duck Yogurt Corner","ركن الزبادي","Passion Fruit Yogurt","زبادي باشن فروت","90",true,7,"yogurt.jpeg"],
    [59,"Duck Smoothies Corner","ركن السموذي","Blueberry Smoothie","سموذي توت أزرق","80",true,1,"smoothies.jpeg"],
    [60,"Duck Smoothies Corner","ركن السموذي","Mango Smoothie","سموذي مانجو","80",true,2,"smoothies.jpeg"],
    [61,"Duck Smoothies Corner","ركن السموذي","Strawberry Smoothie","سموذي فراولة","80",true,3,"smoothies.jpeg"],
    [62,"Duck Smoothies Corner","ركن السموذي","Peach Smoothie","سموذي خوخ","80",true,4,"smoothies.jpeg"],
    [63,"Duck Smoothies Corner","ركن السموذي","Pineapple Smoothie","سموذي أناناس","80",true,5,"smoothies.jpeg"],
    [64,"Duck Smoothies Corner","ركن السموذي","Kiwi Smoothie","سموذي كيوي","80",true,6,"smoothies.jpeg"],
    [65,"Duck Smoothies Corner","ركن السموذي","Passion Fruit Smoothie","سموذي باشن فروت","80",true,7,"smoothies.jpeg"],
    [66,"Duck Smoothies Corner","ركن السموذي","Pinaculada Smoothie","سموذي بينا كولادا","80",true,8,"smoothies.jpeg"],
    [67,"Duck Soda Corner","ركن الصودا","Redbull","ريدبول","85",true,1,"soda.jpeg"],
    [68,"Duck Soda Corner","ركن الصودا","Cherry Cola","شيري كولا","80",true,2,"soda.jpeg"],
    [69,"Duck Soda Corner","ركن الصودا","Jelly Cola","جيلي كولا","80",true,3,"soda.jpeg"],
    [70,"Duck Soda Corner","ركن الصودا","Mojito","موهيتو","80",true,4,"soda.jpeg"],
    [71,"Duck Soda Corner","ركن الصودا","Sunshine","صن شاين","80",true,5,"soda.jpeg"],
    [72,"Duck Soda Corner","ركن الصودا","Soft Drinks","مشروبات غازية","45",true,6,"soda.jpeg"],
    [73,"Duck Soda Corner","ركن الصودا","Mineral Water","مياه معدنية","15",true,7,"soda.jpeg"],
    [74,"Duck Juice Corner","عصائر فريش","Mango","مانجو","80",true,1,"juice.jpeg"],
    [75,"Duck Juice Corner","عصائر فريش","Strawberry","فراولة","70",true,2,"juice.jpeg"],
    [76,"Duck Juice Corner","عصائر فريش","Orange","برتقال","70",true,3,"juice.jpeg"],
    [77,"Duck Juice Corner","عصائر فريش","Guava","جوافة","70",true,4,"juice.jpeg"],
    [78,"Duck Juice Corner","عصائر فريش","Tangerine","يوسفي","70",true,5,"juice.jpeg"],
    [79,"Duck Juice Corner","عصائر فريش","Banana With Milk","موز باللبن","70",true,6,"juice.jpeg"],
    [80,"Duck Juice Corner","عصائر فريش","Guava With Milk","جوافة باللبن","70",true,7,"juice.jpeg"],
    [81,"Duck Juice Corner","عصائر فريش","Lemon Mint","ليمون نعناع","70",true,8,"juice.jpeg"],
    [82,"Duck Boba Corner","ركن البوبا","Blueberry Boba","بوبا توت أزرق","90",true,1,"boba.jpeg"],
    [83,"Duck Boba Corner","ركن البوبا","Strawberry Boba","بوبا فراولة","90",true,2,"boba.jpeg"],
    [84,"Duck Boba Corner","ركن البوبا","Passion Fruit Boba","بوبا باشن فروت","90",true,3,"boba.jpeg"],
    [85,"Duck Extras","إضافات","Extra Espresso","إضافه إسبريسو","30",true,1,"duck.jpeg"],
    [86,"Duck Extras","إضافات","Extra Flavor","إضافة نكهة","20",true,2,"duck.jpeg"],
    [87,"Duck Extras","إضافات","Extra Milk","إضافة حليب","20",true,3,"duck.jpeg"],
    [88,"Duck Extras","إضافات","Extra Sauce","إضافة صوص","20",true,4,"duck.jpeg"],
    [89,"Duck Extras","إضافات","Extra Boba","إضافة بوبا","35",true,5,"duck.jpeg"],
    [90,"Desserts","حلويات","Chocolate Bar Date","بار تمر بالشوكولاتة","30",true,1,"dessert.jpeg"],
    [91,"Desserts","حلويات","Cookies","كوكيز","45",true,2,"dessert.jpeg"],
    [92,"Desserts","حلويات","Brownies","براونيز","55",true,3,"dessert.jpeg"],
    [93,"Desserts","حلويات","Chocolate Cheese Cake","تشيز كيك شوكولاتة","80",true,4,"dessert.jpeg"],
    [94,"Desserts","حلويات","Strawberry Cheese Cake","تشيز كيك فراولة","80",true,5,"dessert.jpeg"],
    [95,"Desserts","حلويات","Lotus Cheese Cake","تشيز كيك لوتس","85",true,6,"dessert.jpeg"],
    [96,"Desserts","حلويات","Ding Dong Cake","دينج دونج كيك","65",true,7,"dessert.jpeg"],
    [97,"Desserts","حلويات","Chocolate Muffin","مافن شوكولاتة","45",true,8,"dessert.jpeg"],
    [98,"Desserts","حلويات","Chocolate Cake","كيك شوكولاتة","75",true,9,"dessert.jpeg"],
    [99,"Desserts","حلويات","Chocolate Date Bar","بار تمر بالشوكولاتة","35",true,10,"dessert.jpeg"],
    [100,"Desserts","حلويات","English Cake","كيك إنجليزي","35",true,11,"dessert.jpeg"],
    [101,"Desserts","حلويات","Marble Cake","كيك ماربل","35",true,12,"dessert.jpeg"],
    [102,"Desserts","حلويات","Lava Cake","لافا كيك","120",true,13,"dessert.jpeg"],
    [103,"Playstation Corner","ركن البلايستيشن","PS5 - Single","بلايستيشن 5 - فردي","80",true,1,"playstation.jpeg"],
    [104,"Playstation Corner","ركن البلايستيشن","PS5 - Multiplayer","بلايستيشن 5 - جماعي","110",true,2,"playstation.jpeg"],
    [105,"Playstation Corner","ركن البلايستيشن","PS4 - Single","بلايستيشن 4 - فردي","60",true,3,"playstation.jpeg"],
    [106,"Playstation Corner","ركن البلايستيشن","PS4 - Multiplayer","بلايستيشن 4 - جماعي","90",true,4,"playstation.jpeg"]
  ];

  sheet.clear();
  sheet.getRange(1, 1, data.length, data[0].length).setValues(data);
}
